Dev
zhoskiy/PPVIS-2 pull request #1
Opened 2020-05-20 10:33 UTC by zhoskiy

2020-05-27 10:50 UTC, Paulbel requested changes
copy of https://github.com/N1kla3/PPVIS-2/pull/1/files 
индивидуально: добавить возможность сортировки в таблице

2020-05-27 10:50 UTC, Paulbel commented on PPVIS-2-SWING/src/com/company/view/AddFrame.java
> +    public JButton add;
private

2020-05-28 11:44 UTC, zhoskiy commented on PPVIS-2-SWING/src/com/company/view/AddFrame.java
> +    public JButton add;
Дело сделано

2020-05-28 11:48 UTC, zhoskiy commented on PPVIS-2-SWING/src/com/company/view/AddFrame.java
> +    public JButton add;
Павел Михайлович, если все хорошо, то ссылку на демо лучше всего в таблицу добавить?
И еще. За каждую лабораторную работу дается 2,5 балла?

2020-06-03 09:47 UTC, Paulbel approved these changes
Удалить директорию out из проекта, разрешить конфликт в readme, прислать демо

2020-06-03 11:04 UTC, merged